// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:49 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.Remoting.Channels
namespace System::Runtime::Remoting::Channels {
  // Autogenerated type: System.Runtime.Remoting.Channels.ISecurableChannel
  class ISecurableChannel {
    public:
    // public System.Void set_IsSecured(System.Boolean value)
    // Offset: 0xFFFFFFFF
    void set_IsSecured(bool value);
  }; // System.Runtime.Remoting.Channels.ISecurableChannel
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::Remoting::Channels::ISecurableChannel*, "System.Runtime.Remoting.Channels", "ISecurableChannel");
#pragma pack(pop)
