// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:45 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Threading.EventWaitHandle
#include "System/Threading/EventWaitHandle.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Threading
namespace System::Threading {
  // Autogenerated type: System.Threading.ManualResetEvent
  class ManualResetEvent : public System::Threading::EventWaitHandle {
    public:
    // public System.Void .ctor(System.Boolean initialState)
    // Offset: 0x13C4C3C
    static ManualResetEvent* New_ctor(bool initialState);
  }; // System.Threading.ManualResetEvent
}
DEFINE_IL2CPP_ARG_TYPE(System::Threading::ManualResetEvent*, "System.Threading", "ManualResetEvent");
#pragma pack(pop)
