// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:56 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Compatibility
namespace NUnit::Compatibility {
  // Autogenerated type: NUnit.Compatibility.NUnitNullType
  class NUnitNullType : public ::Il2CppObject {
  }; // NUnit.Compatibility.NUnitNullType
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Compatibility::NUnitNullType*, "NUnit.Compatibility", "NUnitNullType");
#pragma pack(pop)
