// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Polyglot
namespace Polyglot {
  // Autogenerated type: Polyglot.ILocalize
  class ILocalize {
    public:
    // public System.Void OnLocalize()
    // Offset: 0xFFFFFFFF
    void OnLocalize();
  }; // Polyglot.ILocalize
}
DEFINE_IL2CPP_ARG_TYPE(Polyglot::ILocalize*, "Polyglot", "ILocalize");
#pragma pack(pop)
