// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:57 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: NUnit.Framework.NUnitAttribute
#include "NUnit/Framework/NUnitAttribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework
namespace NUnit::Framework {
  // Autogenerated type: NUnit.Framework.TearDownAttribute
  class TearDownAttribute : public NUnit::Framework::NUnitAttribute {
  }; // NUnit.Framework.TearDownAttribute
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::TearDownAttribute*, "NUnit.Framework", "TearDownAttribute");
#pragma pack(pop)
