// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:06 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Oculus.Platform
namespace Oculus::Platform {
  // Autogenerated type: Oculus.Platform.IMicrophone
  class IMicrophone {
    public:
    // public System.Void Start()
    // Offset: 0xFFFFFFFF
    void Start();
    // public System.Void Stop()
    // Offset: 0xFFFFFFFF
    void Stop();
    // public System.Single[] Update()
    // Offset: 0xFFFFFFFF
    ::Array<float>* Update();
  }; // Oculus.Platform.IMicrophone
}
DEFINE_IL2CPP_ARG_TYPE(Oculus::Platform::IMicrophone*, "Oculus.Platform", "IMicrophone");
#pragma pack(pop)
