// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:29 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.AssemblyIsEditorAssembly
  class AssemblyIsEditorAssembly : public System::Attribute {
  }; // UnityEngine.AssemblyIsEditorAssembly
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::AssemblyIsEditorAssembly*, "UnityEngine", "AssemblyIsEditorAssembly");
#pragma pack(pop)
