// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:29 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.Object
#include "UnityEngine/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.FailedToLoadScriptObject
  class FailedToLoadScriptObject : public UnityEngine::Object {
  }; // UnityEngine.FailedToLoadScriptObject
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::FailedToLoadScriptObject*, "UnityEngine", "FailedToLoadScriptObject");
#pragma pack(pop)
