// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:28 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.ImageEffectOpaque
  class ImageEffectOpaque : public System::Attribute {
    public:
    // public System.Void .ctor()
    // Offset: 0x12FA45C
    // Implemented from: System.Attribute
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static ImageEffectOpaque* New_ctor();
  }; // UnityEngine.ImageEffectOpaque
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::ImageEffectOpaque*, "UnityEngine", "ImageEffectOpaque");
#pragma pack(pop)
