// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:30 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine
namespace UnityEngine {
  // Autogenerated type: UnityEngine.SerializeReference
  class SerializeReference : public System::Attribute {
  }; // UnityEngine.SerializeReference
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::SerializeReference*, "UnityEngine", "SerializeReference");
#pragma pack(pop)
