// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:17 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Collections.ReadOnlyCollectionBase
#include "System/Collections/ReadOnlyCollectionBase.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Diagnostics
namespace System::Diagnostics {
  // Autogenerated type: System.Diagnostics.ProcessModuleCollection
  class ProcessModuleCollection : public System::Collections::ReadOnlyCollectionBase {
  }; // System.Diagnostics.ProcessModuleCollection
}
DEFINE_IL2CPP_ARG_TYPE(System::Diagnostics::ProcessModuleCollection*, "System.Diagnostics", "ProcessModuleCollection");
#pragma pack(pop)
