// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:31 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: UnityEngine.PlayerLoop.FixedUpdate
#include "UnityEngine/PlayerLoop/FixedUpdate.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: UnityEngine.PlayerLoop
namespace UnityEngine::PlayerLoop {
  // Autogenerated type: UnityEngine.PlayerLoop.FixedUpdate/DirectorFixedSampleTime
  struct FixedUpdate::DirectorFixedSampleTime : public System::ValueType {
    // Creating value type constructor for type: DirectorFixedSampleTime
    DirectorFixedSampleTime() {}
  }; // UnityEngine.PlayerLoop.FixedUpdate/DirectorFixedSampleTime
}
DEFINE_IL2CPP_ARG_TYPE(UnityEngine::PlayerLoop::FixedUpdate::DirectorFixedSampleTime, "UnityEngine.PlayerLoop", "FixedUpdate/DirectorFixedSampleTime");
#pragma pack(pop)
