// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:56 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: NUnit.Framework.Interfaces
namespace NUnit::Framework::Interfaces {
  // Autogenerated type: NUnit.Framework.Interfaces.IDisposableFixture
  class IDisposableFixture {
  }; // NUnit.Framework.Interfaces.IDisposableFixture
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Interfaces::IDisposableFixture*, "NUnit.Framework.Interfaces", "IDisposableFixture");
#pragma pack(pop)
