// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:21 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: HMUI
namespace HMUI {
  // Autogenerated type: HMUI.EventSystemHelpers
  class EventSystemHelpers : public ::Il2CppObject {
    public:
    // static public System.Boolean IsInputFieldSelected()
    // Offset: 0xEC3E08
    static bool IsInputFieldSelected();
  }; // HMUI.EventSystemHelpers
}
DEFINE_IL2CPP_ARG_TYPE(HMUI::EventSystemHelpers*, "HMUI", "EventSystemHelpers");
#pragma pack(pop)
