// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:46 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Threading.Tasks
namespace System::Threading::Tasks {
  // Autogenerated type: System.Threading.Tasks.SystemThreadingTasks_TaskDebugView
  class SystemThreadingTasks_TaskDebugView : public ::Il2CppObject {
  }; // System.Threading.Tasks.SystemThreadingTasks_TaskDebugView
}
DEFINE_IL2CPP_ARG_TYPE(System::Threading::Tasks::SystemThreadingTasks_TaskDebugView*, "System.Threading.Tasks", "SystemThreadingTasks_TaskDebugView");
#pragma pack(pop)
