// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:16 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Configuration.ConfigurationElement
#include "System/Configuration/ConfigurationElement.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Configuration
namespace System::Configuration {
  // Autogenerated type: System.Configuration.ConfigurationElementCollection
  class ConfigurationElementCollection : public System::Configuration::ConfigurationElement {
  }; // System.Configuration.ConfigurationElementCollection
}
DEFINE_IL2CPP_ARG_TYPE(System::Configuration::ConfigurationElementCollection*, "System.Configuration", "ConfigurationElementCollection");
#pragma pack(pop)
