// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.ComponentModel.ReferenceConverter
#include "System/ComponentModel/ReferenceConverter.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.ComponentModel
namespace System::ComponentModel {
  // Autogenerated type: System.ComponentModel.ComponentConverter
  class ComponentConverter : public System::ComponentModel::ReferenceConverter {
  }; // System.ComponentModel.ComponentConverter
}
DEFINE_IL2CPP_ARG_TYPE(System::ComponentModel::ComponentConverter*, "System.ComponentModel", "ComponentConverter");
#pragma pack(pop)
