// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:50 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.Remoting.Messaging
namespace System::Runtime::Remoting::Messaging {
  // Autogenerated type: System.Runtime.Remoting.Messaging.IMessageCtrl
  class IMessageCtrl {
  }; // System.Runtime.Remoting.Messaging.IMessageCtrl
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::Remoting::Messaging::IMessageCtrl*, "System.Runtime.Remoting.Messaging", "IMessageCtrl");
#pragma pack(pop)
