// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:56 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Text::RegularExpressions
namespace System::Text::RegularExpressions {
  // Forward declaring type: Regex
  class Regex;
}
// Completed forward declares
// Type namespace: NUnit.Framework.Internal
namespace NUnit::Framework::Internal {
  // Autogenerated type: NUnit.Framework.Internal.StackFilter
  class StackFilter : public ::Il2CppObject {
    public:
    // Get static field: static private readonly System.Text.RegularExpressions.Regex assertOrAssumeRegex
    static System::Text::RegularExpressions::Regex* _get_assertOrAssumeRegex();
    // Set static field: static private readonly System.Text.RegularExpressions.Regex assertOrAssumeRegex
    static void _set_assertOrAssumeRegex(System::Text::RegularExpressions::Regex* value);
    // static public System.String Filter(System.String rawTrace)
    // Offset: 0x18D75FC
    static ::Il2CppString* Filter(::Il2CppString* rawTrace);
    // static private System.Void .cctor()
    // Offset: 0x18D7814
    static void _cctor();
  }; // NUnit.Framework.Internal.StackFilter
}
DEFINE_IL2CPP_ARG_TYPE(NUnit::Framework::Internal::StackFilter*, "NUnit.Framework.Internal", "StackFilter");
#pragma pack(pop)
