// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:46 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IAnimatorIkHandler
  class IAnimatorIkHandler {
    public:
    // public System.Void OnAnimatorIk()
    // Offset: 0xFFFFFFFF
    void OnAnimatorIk();
  }; // Zenject.IAnimatorIkHandler
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::IAnimatorIkHandler*, "Zenject", "IAnimatorIkHandler");
#pragma pack(pop)
