// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:44 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IFactory
  class IFactory {
  }; // Zenject.IFactory
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::IFactory*, "Zenject", "IFactory");
#pragma pack(pop)
