// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:40 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IFixedTickable
  class IFixedTickable {
    public:
    // public System.Void FixedTick()
    // Offset: 0xFFFFFFFF
    void FixedTick();
  }; // Zenject.IFixedTickable
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::IFixedTickable*, "Zenject", "IFixedTickable");
#pragma pack(pop)
