// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:40 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IGuiRenderable
  class IGuiRenderable {
    public:
    // public System.Void GuiRender()
    // Offset: 0xFFFFFFFF
    void GuiRender();
  }; // Zenject.IGuiRenderable
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::IGuiRenderable*, "Zenject", "IGuiRenderable");
#pragma pack(pop)
