// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:45 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: Zenject.InstallerBase
#include "Zenject/InstallerBase.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.Installer
  class Installer : public Zenject::InstallerBase {
    public:
    // protected System.Void .ctor()
    // Offset: 0xF275F0
    // Implemented from: Zenject.InstallerBase
    // Base method: System.Void InstallerBase::.ctor()
    // Base method: System.Void Object::.ctor()
    static Installer* New_ctor();
  }; // Zenject.Installer
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::Installer*, "Zenject", "Installer");
#pragma pack(pop)
