// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:47 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Zenject
namespace Zenject {
  // Autogenerated type: Zenject.IValidatable
  class IValidatable {
    public:
    // public System.Void Validate()
    // Offset: 0xFFFFFFFF
    void Zenject_IValidatable_Validate();
  }; // Zenject.IValidatable
}
DEFINE_IL2CPP_ARG_TYPE(Zenject::IValidatable*, "Zenject", "IValidatable");
#pragma pack(pop)
