// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:44 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Reflection.Assembly
#include "System/Reflection/Assembly.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Reflection.Emit
namespace System::Reflection::Emit {
  // Autogenerated type: System.Reflection.Emit.AssemblyBuilder
  class AssemblyBuilder : public System::Reflection::Assembly {
  }; // System.Reflection.Emit.AssemblyBuilder
}
DEFINE_IL2CPP_ARG_TYPE(System::Reflection::Emit::AssemblyBuilder*, "System.Reflection.Emit", "AssemblyBuilder");
#pragma pack(pop)
