// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:51 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.InteropServices
namespace System::Runtime::InteropServices {
  // Autogenerated type: System.Runtime.InteropServices._FieldInfo
  class _FieldInfo {
  }; // System.Runtime.InteropServices._FieldInfo
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::InteropServices::_FieldInfo*, "System.Runtime.InteropServices", "_FieldInfo");
#pragma pack(pop)
