// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:39 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.ContextStaticAttribute
  class ContextStaticAttribute : public System::Attribute {
    public:
    // public System.Void .ctor()
    // Offset: 0x10AF7CC
    // Implemented from: System.Attribute
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static ContextStaticAttribute* New_ctor();
  }; // System.ContextStaticAttribute
}
DEFINE_IL2CPP_ARG_TYPE(System::ContextStaticAttribute*, "System", "ContextStaticAttribute");
#pragma pack(pop)
