// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:41 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.SByteEnum
  struct SByteEnum : public System::Enum {
    public:
    // public System.SByte value__
    // Offset: 0x0
    int8_t value;
    // Creating value type constructor for type: SByteEnum
    SByteEnum(int8_t value_ = {}) : value{value_} {}
  }; // System.SByteEnum
}
DEFINE_IL2CPP_ARG_TYPE(System::SByteEnum, "System", "SByteEnum");
#pragma pack(pop)
