// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:41 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Enum
#include "System/Enum.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System
namespace System {
  // Autogenerated type: System.UInt16Enum
  struct UInt16Enum : public System::Enum {
    public:
    // public System.UInt16 value__
    // Offset: 0x0
    uint16_t value;
    // Creating value type constructor for type: UInt16Enum
    UInt16Enum(uint16_t value_ = {}) : value{value_} {}
  }; // System.UInt16Enum
}
DEFINE_IL2CPP_ARG_TYPE(System::UInt16Enum, "System", "UInt16Enum");
#pragma pack(pop)
