// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:47 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: System.Runtime.Serialization
namespace System::Runtime::Serialization {
  // Autogenerated type: System.Runtime.Serialization.ISafeSerializationData
  class ISafeSerializationData {
    public:
    // public System.Void CompleteDeserialization(System.Object deserialized)
    // Offset: 0xFFFFFFFF
    void CompleteDeserialization(::Il2CppObject* deserialized);
  }; // System.Runtime.Serialization.ISafeSerializationData
}
DEFINE_IL2CPP_ARG_TYPE(System::Runtime::Serialization::ISafeSerializationData*, "System.Runtime.Serialization", "ISafeSerializationData");
#pragma pack(pop)
