// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:40 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: JetBrains.Annotations
namespace JetBrains::Annotations {
  // Autogenerated type: JetBrains.Annotations.CannotApplyEqualityOperatorAttribute
  class CannotApplyEqualityOperatorAttribute : public System::Attribute {
    public:
    // public System.Void .ctor()
    // Offset: 0x19452B8
    // Implemented from: System.Attribute
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static CannotApplyEqualityOperatorAttribute* New_ctor();
  }; // JetBrains.Annotations.CannotApplyEqualityOperatorAttribute
}
DEFINE_IL2CPP_ARG_TYPE(JetBrains::Annotations::CannotApplyEqualityOperatorAttribute*, "JetBrains.Annotations", "CannotApplyEqualityOperatorAttribute");
#pragma pack(pop)
