// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:27 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: System.Attribute
#include "System/Attribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: Unity.Collections
namespace Unity::Collections {
  // Autogenerated type: Unity.Collections.WriteOnlyAttribute
  class WriteOnlyAttribute : public System::Attribute {
  }; // Unity.Collections.WriteOnlyAttribute
}
DEFINE_IL2CPP_ARG_TYPE(Unity::Collections::WriteOnlyAttribute*, "Unity.Collections", "WriteOnlyAttribute");
#pragma pack(pop)
