// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:24 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: BeatmapSaveData
#include "GlobalNamespace/BeatmapSaveData.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: BeatmapSaveData/ITime
  class BeatmapSaveData::ITime {
    public:
    // public System.Single get_time()
    // Offset: 0xFFFFFFFF
    float get_time();
    // public System.Void MoveTime(System.Single offset)
    // Offset: 0xFFFFFFFF
    void MoveTime(float offset);
  }; // BeatmapSaveData/ITime
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::BeatmapSaveData::ITime*, "", "BeatmapSaveData/ITime");
#pragma pack(pop)
