// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:19 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: GenericSignal`1
#include "GlobalNamespace/GenericSignal_1.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: BoolSignal
  class BoolSignal : public GlobalNamespace::GenericSignal_1<bool> {
    public:
    // public System.Void .ctor()
    // Offset: 0xC980C4
    // Implemented from: GenericSignal`1
    // Base method: System.Void GenericSignal`1::.ctor()
    // Base method: System.Void Signal::.ctor()
    // Base method: System.Void ScriptableObject::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    static BoolSignal* New_ctor();
  }; // BoolSignal
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::BoolSignal*, "", "BoolSignal");
#pragma pack(pop)
