// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:20 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: CameraRenderCallbacksManager
#include "GlobalNamespace/CameraRenderCallbacksManager.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: Camera
  class Camera;
}
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: CameraRenderCallbacksManager/ICameraRenderCallbacks
  class CameraRenderCallbacksManager::ICameraRenderCallbacks {
    public:
    // public System.Void OnCameraPostRender(UnityEngine.Camera camera)
    // Offset: 0xFFFFFFFF
    void OnCameraPostRender(UnityEngine::Camera* camera);
    // public System.Void OnCameraPreRender(UnityEngine.Camera camera)
    // Offset: 0xFFFFFFFF
    void OnCameraPreRender(UnityEngine::Camera* camera);
  }; // CameraRenderCallbacksManager/ICameraRenderCallbacks
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::CameraRenderCallbacksManager::ICameraRenderCallbacks*, "", "CameraRenderCallbacksManager/ICameraRenderCallbacks");
#pragma pack(pop)
