// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:23 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: IAudioTimeSource
  class IAudioTimeSource {
    public:
    // public System.Single get_songTime()
    // Offset: 0xFFFFFFFF
    float get_songTime();
  }; // IAudioTimeSource
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::IAudioTimeSource*, "", "IAudioTimeSource");
#pragma pack(pop)
