// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:30 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: ILevelRestartController
  class ILevelRestartController {
    public:
    // public System.Void RestartLevel()
    // Offset: 0xFFFFFFFF
    void RestartLevel();
  }; // ILevelRestartController
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::ILevelRestartController*, "", "ILevelRestartController");
#pragma pack(pop)
