// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:18 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: IManualUpdate
  class IManualUpdate {
    public:
    // public System.Void ManualUpdate()
    // Offset: 0xFFFFFFFF
    void ManualUpdate();
  }; // IManualUpdate
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::IManualUpdate*, "", "IManualUpdate");
#pragma pack(pop)
