// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:37 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: IAudioClipAsyncLoader
#include "GlobalNamespace/IAudioClipAsyncLoader.hpp"
// Including type: IImageAsyncLoader
#include "GlobalNamespace/IImageAsyncLoader.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: IMediaAsyncLoader
  class IMediaAsyncLoader : public GlobalNamespace::IAudioClipAsyncLoader, public GlobalNamespace::IImageAsyncLoader {
  }; // IMediaAsyncLoader
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::IMediaAsyncLoader*, "", "IMediaAsyncLoader");
#pragma pack(pop)
