// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:10 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.PropertyAttribute
#include "UnityEngine/PropertyAttribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: LocalizationKeyAttribute
  class LocalizationKeyAttribute : public UnityEngine::PropertyAttribute {
    public:
    // public System.Void .ctor()
    // Offset: 0x18FD060
    // Implemented from: UnityEngine.PropertyAttribute
    // Base method: System.Void PropertyAttribute::.ctor()
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static LocalizationKeyAttribute* New_ctor();
  }; // LocalizationKeyAttribute
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::LocalizationKeyAttribute*, "", "LocalizationKeyAttribute");
#pragma pack(pop)
