// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:00 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: OVRMesh
#include "GlobalNamespace/OVRMesh.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRMesh/IOVRMeshDataProvider
  class OVRMesh::IOVRMeshDataProvider {
    public:
    // public OVRMesh/MeshType GetMeshType()
    // Offset: 0xFFFFFFFF
    GlobalNamespace::OVRMesh::MeshType GlobalNamespace_OVRMesh_IOVRMeshDataProvider_GetMeshType();
  }; // OVRMesh/IOVRMeshDataProvider
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRMesh::IOVRMeshDataProvider*, "", "OVRMesh/IOVRMeshDataProvider");
#pragma pack(pop)
