// Autogenerated from CppHeaderCreator on 7/27/2020 3:10:00 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: OVRSkeleton
#include "GlobalNamespace/OVRSkeleton.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRSkeleton/IOVRSkeletonDataProvider
  class OVRSkeleton::IOVRSkeletonDataProvider {
    public:
    // public OVRSkeleton/SkeletonType GetSkeletonType()
    // Offset: 0xFFFFFFFF
    GlobalNamespace::OVRSkeleton::SkeletonType GlobalNamespace_OVRSkeleton_IOVRSkeletonDataProvider_GetSkeletonType();
    // public OVRSkeleton/SkeletonPoseData GetSkeletonPoseData()
    // Offset: 0xFFFFFFFF
    GlobalNamespace::OVRSkeleton::SkeletonPoseData GlobalNamespace_OVRSkeleton_IOVRSkeletonDataProvider_GetSkeletonPoseData();
  }; // OVRSkeleton/IOVRSkeletonDataProvider
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRSkeleton::IOVRSkeletonDataProvider*, "", "OVRSkeleton/IOVRSkeletonDataProvider");
#pragma pack(pop)
