// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:57 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
#include "utils/typedefs.h"
// Including type: System.Object
#include "System/Object.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: OVRSandwichComposition
  class OVRSandwichComposition : public ::Il2CppObject {
    public:
    // public System.Void .ctor()
    // Offset: 0xF37404
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    static OVRSandwichComposition* New_ctor();
  }; // OVRSandwichComposition
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::OVRSandwichComposition*, "", "OVRSandwichComposition");
#pragma pack(pop)
