// Autogenerated from CppHeaderCreator on 7/27/2020 3:09:19 PM
// Created by Sc2ad
// =========================================================================
#pragma once
#pragma pack(push, 8)
// Begin includes
// Including type: UnityEngine.PropertyAttribute
#include "UnityEngine/PropertyAttribute.hpp"
#include "utils/il2cpp-utils.hpp"
// Completed includes
// Begin forward declares
// Completed forward declares
// Type namespace: 
namespace GlobalNamespace {
  // Autogenerated type: SignalSenderAttribute
  class SignalSenderAttribute : public UnityEngine::PropertyAttribute {
    public:
    // public System.Void .ctor()
    // Offset: 0xCA731C
    // Implemented from: UnityEngine.PropertyAttribute
    // Base method: System.Void PropertyAttribute::.ctor()
    // Base method: System.Void Attribute::.ctor()
    // Base method: System.Void Object::.ctor()
    static SignalSenderAttribute* New_ctor();
  }; // SignalSenderAttribute
}
DEFINE_IL2CPP_ARG_TYPE(GlobalNamespace::SignalSenderAttribute*, "", "SignalSenderAttribute");
#pragma pack(pop)
